### ISSUE TITLE
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: 用户的配置文件是临时配置文件

### ISSUE THREAD

**Issue by ToTovlen** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#155]
请简要描述你所遇到的问题。
使用 SKIT.FlurlHttpClient.Wechat.TenpayV3 调用微信原生支付，出现错误：
[ERR] Failed to sign request. Please see the inner exception for more details.
SKIT.FlurlHttpClient.Wechat.TenpayV3.WechatTenpayException: Failed to sign request. Please see the inner exception for more details.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: 用户的配置文件是临时配置文件。
   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.RSAImplementation.RSACng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at SKIT.FlurlHttpClient.Wechat.TenpayV3.Utilities.RSAUtility.SignWithSHA256(Byte[] privateKeyBytes, Byte[] messageBytes)
   at SKIT.FlurlHttpClient.Wechat.TenpayV3.Utilities.RSAUtility.SignWithSHA256(String privateKeyPem, String messageData)
   at SKIT.FlurlHttpClient.Wechat.TenpayV3.Interceptors.WechatTenpayRequestSigningInterceptor.BeforeCallAsync(HttpInterceptorContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at SKIT.FlurlHttpClient.Wechat.TenpayV3.Interceptors.WechatTenpayRequestSigningInterceptor.BeforeCallAsync(HttpInterceptorContext context, CancellationToken cancellationToken)
   at SKIT.FlurlHttpClient.CommonClientBase.<>c__DisplayClass12_0.<<-ctor>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Flurl.Http.FlurlClient.RaiseEventAsync(FlurlEventType eventType, FlurlCall call)
   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at SKIT.FlurlHttpClient.CommonClientBase.SendFlurlRequestAsync(IFlurlRequest flurlRequest, HttpContent httpContent, CancellationToken cancellationToken)
   at SKIT.FlurlHttpClient.CommonClientBase.SendFlurlRequestAsJsonAsync(IFlurlRequest flurlRequest, Object data, CancellationToken cancellationToken)
   at SKIT.FlurlHttpClient.Wechat.TenpayV3.WechatTenpayClient.SendFlurlRequestAsJsonAsync[T](IFlurlRequest flurlRequest, Object data, CancellationToken cancellationToken)
   at SKIT.FlurlHttpClient.Wechat.TenpayV3.WechatTenpayClientExecutePayTransactionsExtensions.ExecuteCreatePayTransactionNativeAsync(WechatTenpayClient client, CreatePayTransactionNativeRequest request, CancellationToken cancellationToken)
   at Boolv.PaymentSys.Api.Application.PaymentService.WxNativePayTransactions(String ProductCode, String AppId, String Sign, WeiXinNativePayRequest model) in D:\Work\Project\Boolv.Payment.Sys\Boolv.PaymentSys.Api.Application\Payment\PaymentService.cs:line 338
   at lambda_method409(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

请问是什么问题？

**Comment by fudiwei** [comment]
IIS？设置里把“加载用户配置文件”勾上。

**Comment by fudiwei** [comment]
Issue 太久没有活跃，暂时关闭。如有需要，请重新打开。
