### ISSUE TITLE
[BUG] tenpay v3 2.1.2 版本jsapi下单加解密异常

### ISSUE THREAD

**Issue by LuohuaRain** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#17]
---

**关于问题的简单描述**

JSAPI 下单时直接异常

---

**与问题相关的源代码**

```csharp
 var payRequest = new CreatePayTransactionJsapiRequest
        {
            Amount = new CreatePayTransactionJsapiRequest.Types.Amount { Total = Amount },
            AppId = _wxApiClient.Credentials.AppId,
            Description = $"支付",
            NotifyUrl = NotifyUrl,
            Payer = new CreatePayTransactionJsapiRequest.Types.Payer { OpenId = openId },
            OutTradeNumber = $"{studentId}{DateTimeOffset.Now:yyyyMMddHHmmssfff}",
        };
        var payResponse = await _payClient.ExecuteCreatePayTransactionJsapiAsync(payRequest, cancellationToken: HttpContext.RequestAborted);
```

---

**异常堆栈或异常原因**

> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      SKIT.FlurlHttpClient.Wechat.TenpayV3.Exceptions.WechatTenpayResponseDecryptionException: Decrypt response failed. Please see the `InnerException` for more details.
       ---> System.NotSupportedException: Collection is read-only.
         at System.Collections.ObjectModel.ReadOnlyDictionary`2.System.Collections.IDictionary.set_Item(Object key, Object value)
         at SKIT.FlurlHttpClient.Wechat.TenpayV3.Utilities.ReflectionUtility.InnerReplaceEachCollectionPropertyStringValue[T](T& obj, Type objType, ReplacePropertyStringValueReplacement replacement, PropertyInfo currentProp)
         at SKIT.FlurlHttpClient.Wechat.TenpayV3.Utilities.ReflectionUtility.InnerReplacePropertyStringValue[T](T& obj, ReplacePropertyStringValueReplacement replacement, PropertyInfo currentProp)
         at SKIT.FlurlHttpClient.Wechat.TenpayV3.Utilities.ReflectionUtility.ReplacePropertyStringValue[T](T& obj, ReplacePropertyStringValueReplacement replacement)
         at SKIT.FlurlHttpClient.Wechat.TenpayV3.WechatTenpayClientResponseDecryptionExtensions.DecryptResponseSensitiveProperty[TResponse](WechatTenpayClient client, TResponse response)
         --- End of inner exception stack trace ---
         at SKIT.FlurlHttpClient.Wechat.TenpayV3.WechatTenpayClientResponseDecryptionExtensions.DecryptResponseSensitiveProperty[TResponse](WechatTenpayClient client, TResponse response)
         at SKIT.FlurlHttpClient.Wechat.TenpayV3.WechatTenpayClient.GetResposneAsync[T](IFlurlResponse flurlResponse)
         at SKIT.FlurlHttpClient.Wechat.TenpayV3.WechatTenpayClient.SendRequestWithJsonAsync[T](IFlurlRequest flurlRequest, Object data, CancellationToken cancellationToken)
         at SKIT.FlurlHttpClient.Wechat.TenpayV3.WechatTenpayClientExecutePayTransactionsExtensions.ExecuteCreatePayTransactionJsapiAsync(WechatTenpayClient client, CreatePayTransactionJsapiRequest request, CancellationToken cancellationToken)

---

**发生问题的运行环境**

请在此填写以下几项内容：

1. 操作系统：Win 10 pro
2. .NET 版本：.NET 6.0
3. 使用的模块及版本：SKIT.FlurlHttpClient.Wechat.TenpayV3 2.1.2

---

**补充说明**

SKIT.FlurlHttpClient.Wechat.TenpayV3 2.1.1 没有问题
更新至 SKIT.FlurlHttpClient.Wechat.TenpayV3 2.1.2 后报此错误。

  >  "AutoEncryptRequestSensitiveProperty": true,
    "AutoDecryptResponseSensitiveProperty": true

**Comment by fudiwei** [comment]
感谢指出，已在 [v2.1.3](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.TenpayV3/2.1.3) 中修复，同时补充了存在 `ReadOnlyArray`/`ReadOnlyList`/`ReadOnlyDictionary` 属性的相关测试用例。
