### ISSUE TITLE
[BUG] Deserialize NotifyThirdFastRegisterEvent The XML element 'legal_persona_wechat' from namespace '' is already present in the current scope

### ISSUE THREAD

**Issue by code-jar** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#67]
---

**关于问题的简单描述**

反序列化小程序注册事件发生异常，提示The XML element 'legal_persona_wechat' from namespace '' is already present in the current scope

---

**与问题相关的源代码**

```csharp
var registerData = wxClient.DeserializeEventFromXml<NotifyThirdFastRegisterEvent>(body);
```

---

**异常堆栈或异常原因**

```
SKIT.FlurlHttpClient.Wechat.Api.Exceptions.WechatApiEventSerializationException: Deserialize event failed. Please see the `InnerException` for more details.
 ---> System.InvalidOperationException: There was an error reflecting type 'SKIT.FlurlHttpClient.Wechat.Api.Events.NotifyThirdFastRegisterEvent'.
 ---> System.InvalidOperationException: There was an error reflecting property 'InfoData'.
 ---> System.InvalidOperationException: There was an error reflecting type 'SKIT.FlurlHttpClient.Wechat.Api.Events.NotifyThirdFastRegisterEvent.Types.InfoData'.
 ---> System.InvalidOperationException: There was an error reflecting property 'IdName'.
 ---> System.InvalidOperationException: The XML element 'legal_persona_wechat' from namespace '' is already present in the current scope. Use XML attributes to specify another XML name or namespace for the element.
   at System.Xml.Serialization.XmlReflectionImporter.AddUniqueAccessor(INameScope scope, Accessor accessor)
   at System.Xml.Serialization.XmlReflectionImporter.AddUniqueAccessor(MemberMapping member, INameScope elements, INameScope attributes, Boolean isSequence)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(MemberMapping accessor, FieldModel model, XmlAttributes a, String ns, Type choiceIdentifierType, Boolean rpc, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportFieldMapping(StructModel parent, FieldModel model, XmlAttributes a, String ns, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportElement(TypeModel model, XmlRootAttribute root, String defaultNamespace, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer.GenerateXmlTypeMapping(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, XmlAttributeOverrides overrides, Type[] extraTypes, XmlRootAttribute root, String defaultNamespace, String location)
   at SKIT.FlurlHttpClient.Wechat.Api.Utilities.XmlUtility.GetTypedSerializer(Type type)
   at SKIT.FlurlHttpClient.Wechat.Api.Utilities.XmlUtility.Deserialize(Type type, String xml)
   at SKIT.FlurlHttpClient.Wechat.Api.Utilities.XmlUtility.Deserialize[T](String xml)
   at SKIT.FlurlHttpClient.Wechat.Api.WechatApiClientEventExtensions.InnerDeserializeEventFromXml[TEvent](WechatApiClient client, String callbackXml)
```

---

**发生问题的运行环境**

请在此填写以下几项内容：

1. 操作系统：win11
2. .NET 版本：net6.0
3. 使用的模块及版本：SKIT.FlurlHttpClient.Wechat.Api 2.20.0
4. 其他环境信息。

---

**Comment by fudiwei** [comment]
Fix this on release [v2.20.1](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Api/2.20.1).
