### ISSUE TITLE
[BUG] 智能对话接口过时

### ISSUE THREAD

**Issue by WhileKing** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#69]
---

[智能对话文档（签名、智能对话）](https://developers.weixin.qq.com/doc/aispeech/confapi/INTERFACEDOCUMENT.htm)

关于**智能对话**的接口，仓库中的实现有如下几个问题：
1. `SignRequest`与`AIBotRequest`根据目前的文档，不需要加密。目前代码里实现了`WechatOpenAIPlatformRequest.Serialization.IEncryptedXmlable`接口，导致这两个接口进行了加密，从而请求失败。
2. `AIBotResponse`结构已更新，无需`data`包裹。

---

**与问题相关的源代码**

```csharp
public class TestCase_AIBotTests
{
    [Fact(DisplayName = "测试用例：智能对话")]
    public async void TestSendMessage()
    {
        var client = new TestClients();

        var signRequest = new SignRequest()
        {
            UserId = "test"
        };
        var signResponse = await TestClients.InstanceForPlatform.ExecuteSignAsync(signRequest);


        var request = new AIBotRequest()
        {
            Signature = signResponse.Signature,
            QueryString = "你说啥",
            Timeout = 36000
        };

        var response = await TestClients.InstanceForPlatform.ExecuteAIBotAsync(request);
        var str = Encoding.UTF8.GetString(response.RawBytes);
        Console.WriteLine(response);
    }
}
```

---

**异常堆栈或异常原因**

```textplain
System.InvalidOperationException: There was an error generating the XML document.

System.InvalidOperationException
There was an error generating the XML document.
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces)
   at SKIT.FlurlHttpClient.Wechat.OpenAI.Utilities.XmlUtility.Serialize(Type type, Object obj) in C:\Users\dell\RiderProjects\DotNetCore.SKIT.FlurlHttpClient.Wechat\src\SKIT.FlurlHttpClient.Wechat.OpenAI\Utilities\Internal\XmlUtility.cs:line 48
   at SKIT.FlurlHttpClient.Wechat.OpenAI.Utilities.XmlUtility.Serialize[T](T obj) in C:\Users\dell\RiderProjects\DotNetCore.SKIT.FlurlHttpClient.Wechat\src\SKIT.FlurlHttpClient.Wechat.OpenAI\Utilities\Internal\XmlUtility.cs:line 60
   at SKIT.FlurlHttpClient.Wechat.OpenAI.WechatOpenAIPlatformClient.SendRequestWithJsonAsync[T](IFlurlRequest flurlRequest, Object data, CancellationToken cancellationToken) in C:\Users\dell\RiderProjects\DotNetCore.SKIT.FlurlHttpClient.Wechat\src\SKIT.FlurlHttpClient.Wechat.OpenAI\WechatOpenAIPlatformClient.cs:line 105
   at SKIT.FlurlHttpClient.Wechat.OpenAI.WechatOpenAIPlatformClientExecuteQueryExtensions.ExecuteSignAsync(WechatOpenAIPlatformClient client, SignRequest request, CancellationToken cancellationToken) in C:\Users\dell\RiderProjects\DotNetCore.SKIT.FlurlHttpClient.Wechat\src\SKIT.FlurlHttpClient.Wechat.OpenAI\Extensions\Platform\WechatOpenAIPlatformClientExecuteQueryExtensions.cs:line 27
   at SKIT.FlurlHttpClient.Wechat.OpenAI.UnitTests.TestCase_AIBotTests.TestSendMessage() in C:\Users\dell\RiderProjects\DotNetCore.SKIT.FlurlHttpClient.Wechat\test\SKIT.FlurlHttpClient.Wechat.OpenAI.UnitTests\TestCase_AIBotTests.cs:line 20
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__0() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\AsyncTestSyncContext.cs:line 58

System.InvalidOperationException
The type SKIT.FlurlHttpClient.Wechat.OpenAI.Models.Platform.SignRequest was not expected. Use the XmlInclude or SoapInclude attribute to specify types that are not known statically.
   at System.Xml.Serialization.XmlSerializationWriter.WriteTypedPrimitive(String name, String ns, Object o, Boolean xsiType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write1_Object(String n, String ns, Object o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterObject.Write2_xml(Object o)
```

---

**发生问题的运行环境**

请在此填写以下几项内容：

1. 操作系统：Windows 11
3. .NET 版本：.NET 6
4. 使用的模块及版本：SKIT.FlurlHttpClient.Wechat.OpenAI 2.0.0-rc7

---

**补充说明**

无

**Comment by fudiwei** [comment]
@WhileKing 我手头没有可供测试的账号，能否帮我确认一下下面这个接口的返回值具体是什么？文档上并没有给出示例。

> https://developers.weixin.qq.com/doc/aispeech/confapi/mp/getbindlist.html

**Comment by WhileKing** [comment]
> @WhileKing 我手头没有可供测试的账号，能否帮我确认一下下面这个接口的返回值具体是什么结构的？文档上并没有给出示例。
> 
> > https://developers.weixin.qq.com/doc/aispeech/confapi/mp/getbindlist.html

```json
{
    "bindlist": [
        {
            "info": {
                "authorizer_info": {
                    "nick_name": "公众号名称",
                    "head_img": "公众号头像",
                    "service_type_info": {
                        "id": 1
                    },
                    "verify_type_info": {
                        "id": -1
                    },
                    "user_name": "未知, gh_xxxxxxx",
                    "alias": "公众号基础信息-微信号"
                    "qrcode_url": "公众号二维码URL",
                    "business_info": {
                        "open_pay": 0,
                        "open_shake": 0,
                        "open_scan": 0,
                        "open_card": 0,
                        "open_store": 0
                    },
                    "idc": 1,
                    "principal_name": "公众号基础信息-账号主体，如：个人",
                    "signature": "公众号简介",
                    "account_status": 1
                },
                "authorization_info": null,
                "binded": true,
                "authorizer_appid": "授权方的appid"
            }
        }
    ]
}
```

**Comment by WhileKing** [comment]
我只绑定了公众号，测试环境的。所以只返回了一个对象，仅供参考。有几个信息找不到对应的地方（像user_name, idc）

**Comment by fudiwei** [comment]
Release [v2.0.0](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.OpenAI/2.0.0).
