### ISSUE TITLE
[BUG] 企业微信wechat_channels 异常

### ISSUE THREAD

**Issue by lucky19k** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#8]
异常信息：

  SKIT.FlurlHttpClient.Wechat.Work.WechatWorkException: Response could not be deserialized to JSON: GET https://qyapi.weixin.qq.com/cgi-bin/user/list?access_token=&department_id=1&fetch_child=1
   ---> Flurl.Http.FlurlParsingException: Response could not be deserialized to JSON: GET https://qyapi.weixin.qq.com/cgi-bin/user/list?access_token=****&department_id=1&fetch_child=1
   ---> System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.userlist[0].external_profile.wechat_channels | LineNumber: 0 | BytePositionInLine: 481.
   ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.
     at System.Text.Json.Utf8JsonReader.GetString()
     at System.Text.Json.Serialization.Converters.StringConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
     at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
     at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
     at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
     at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
     at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
     at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
     at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
     at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)

查看了下微信文档
结构应该为 
 "wechat_channels": {
                "nickname": "视频号名称",
                "status": 1
            },
对象

源码中为：

public class CgibinUserCreateRequest : WechatWorkRequest
    /// <summary>
    /// 获取或设置视频号名称。
    /// </summary>
    [Newtonsoft.Json.JsonProperty("wechat_channels")]
    [System.Text.Json.Serialization.JsonPropertyName("wechat_channels")]
    public string? WechatChannels { get; set; }

**Comment by fudiwei** [comment]
Bug Confirmed.

TBD.

**Comment by fudiwei** [comment]
Fix this on [release v1.3.2](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Work/1.3.2).

感谢指出，下次知道如何修复的 Bug 欢迎直接 PR~

**Comment by lucky19k** [comment]
好的
